version: '3.8'
services:
  db:
    image: nouchka/sqlite3:latest  # Образ для SQLite
    volumes:
      - ./db:/data  # Монтируем ./db на хосте в /data в контейнере
    networks:
      - appnet
    environment:
      - DB_PATH=/data/BD_kurs_clients.db  # Путь к базе данных в контейнере
    restart: unless-stopped
  telebot:
    image: starchi1/kv:latest
    build:
      context: .  # Путь до директории с Dockerfile
    volumes:
      - ./app/bot.py:/app/bot.py  # Монтируем скрипт бота в контейнер

      # Монтируем базу данных
      - ./db:/app/db  # Путь до базы данных в контейнере
    environment:
      - TELEGRAM_BOT_TOKEN=7588601604:AAFGdFd-_Gafzd2lZ94UFCl_5CYnb6gjw28  # Токен бота
      - DB_PATH=/app/db/BD_kurs_clients.db  # Путь к базе данных для бота в контейнере
    depends_on:
      - db
    networks:
      - appnet
    restart: unless-stopped
networks:
  appnet:
    driver: bridge
